### PR TITLE
Implemented authentication caching

### PR DESCRIPTION
**Pull request by jobec**
Fix for issue #5 

**the signature for __init__ in the InfobloxNetMRI class is changed because of this!**

### CODE REVIEW

**Comment by jobec** [comment]
TODO:  Rewrite unit tests to reflect new signature

**Comment by johnbelamaric** [comment]
Fantastic - it's practically a re-write but that's OK :)

Nice work and thank you!

**Comment by jobec** [comment]
Oh well :) It was an opportunity to allign it a bit more with the Perl API.
And also, it was a good excuse to learn how to write tests. Never did that before.

Maybe double check if the default value for use_ssl and ssl_verify are acceptable. The __init__ method also still needs a docstring so it get's nicely documented when generating the documentation.

**Comment by jobec** [comment]
Any plans on releasing a new version any time soon?
We're running the "straight-from-github" version now, but being able to install it the regular way would be more convenient.

**Comment by johnbelamaric** [comment]
Yes, ok, will do.

On Feb 19, 2016, at 7:37 AM, Joris Beckers <notifications@github.com<mailto:notifications@github.com>> wrote:


Any plans on releasing a new version any time soon?
We're running the "straight-from-github" version now, but being able to install it the regular way would be more convenient.

**Pull request merged**
